# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    serializer:
        serialize_null: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    format_listener:
        rules:
            - { path: '^/', fallback_format: 'json', priorities: [ 'json' ] }
    param_fetcher_listener:  force
    exception:
        enabled: true
        codes:
            { App\Exception\ResourceValidationException: 400 }
#    allowed_methods_listener:  true
#    routing_loader: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.